import { CircleDollarSign, RotateCcw } from 'lucide-react';
import { AdminEmpty, AdminError, AdminPanel, formatAdminDateTime, formatAdminMoney } from '@/components/admin-ui';
import { AdminSlipActions } from '@/components/admin-slip-actions';
import type { AdminPaymentStatus, AdminTransactionBooking, AdminTransactionRefund } from '@/lib/api';

const PAYMENT_LABELS: Record<AdminPaymentStatus, string> = { EXEMPT: 'ยกเว้นชำระเงิน', AWAITING_SLIP: 'รอสลิป', VERIFIED: 'ตรวจสอบแล้ว', FAILED: 'ตรวจสอบไม่ผ่าน' };
const PAYMENT_STYLES: Record<AdminPaymentStatus, string> = { EXEMPT: 'bg-[#edf4ff] text-[#2563eb]', AWAITING_SLIP: 'bg-[#fff4df] text-[#9a570f]', VERIFIED: 'bg-[#e7f8ef] text-[#147653]', FAILED: 'bg-[#fff0ef] text-[#b42318]' };
const REFUND_STYLES = { PENDING: 'bg-[#fff4df] text-[#9a570f]', APPROVED: 'bg-[#eaf2ff] text-[#2459b5]', REJECTED: 'bg-[#fff0ef] text-[#b42318]', PROCESSED: 'bg-[#e7f8ef] text-[#147653]' } as const;

export function AdminPaymentsScreen({ items, loading, error }: { items: AdminTransactionBooking[]; loading: boolean; error: string }) {
  return <AdminPanel title="สถานะการชำระเงิน" description="หนึ่งแถวต่อ Booking; รายการชำระรวมจะแสดงยอดบูธและยอดรวมแยกกัน">
    {error ? <AdminError message={error} /> : loading ? <LoadingRows /> : items.length === 0 ? <AdminEmpty icon={CircleDollarSign} title="ไม่พบบันทึกการชำระเงิน" description="ลองเปลี่ยนตัวกรองสถานะหรือช่วงวันที่" /> : <div className="overflow-x-auto"><table className="w-full min-w-[1080px] border-collapse text-left text-sm"><thead className="bg-[#faf8fc] text-[11px] text-muted"><tr><th className="px-5 py-3">รหัสจอง</th><th className="px-4 py-3">ผู้ขาย / ร้าน</th><th className="px-4 py-3">อีเวนต์</th><th className="px-4 py-3">ยอด</th><th className="px-4 py-3">สถานะชำระ</th><th className="px-4 py-3">หลักฐาน</th><th className="px-4 py-3">เวลา</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-[#eee9f3] align-top"><td className="px-5 py-4 font-black">{item.bookingCode}</td><td className="px-4 py-4"><strong className="block">{item.shop.name}</strong><span className="text-xs text-muted">{item.vendor.fullName}</span></td><td className="px-4 py-4">{item.event.name}</td><td className="px-4 py-4"><strong className="block">บูธ {formatAdminMoney(item.boothPrice)}</strong>{item.paymentGroup ? <span className="mt-1 block text-xs font-bold text-violet">ชำระรวม {item.paymentGroup.paymentCode} · ยอดกลุ่ม {formatAdminMoney(item.paymentGroup.totalAmount)}</span> : <span className="text-xs text-muted">ชำระราย Booking</span>}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${PAYMENT_STYLES[item.paymentStatus]}`}>{PAYMENT_LABELS[item.paymentStatus]}</span></td><td className="px-4 py-4">{item.paymentStatus === 'EXEMPT' ? <span className="text-xs text-muted">ไม่มีสลิป</span> : <AdminSlipActions bookingId={item.id} />}</td><td className="px-4 py-4 text-xs text-muted">{formatAdminDateTime(item.paymentEffectiveAt)}</td></tr>)}</tbody></table></div>}
  </AdminPanel>;
}

export function AdminRefundsScreen({ items, loading, error }: { items: AdminTransactionRefund[]; loading: boolean; error: string }) {
  return <AdminPanel title="คำร้องคืนเงิน" description="แสดงคำร้องจริง ไม่ใช่การอนุมานจากสถานะ Booking">
    {error ? <AdminError message={error} /> : loading ? <LoadingRows /> : items.length === 0 ? <AdminEmpty icon={RotateCcw} title="ไม่พบคำร้องคืนเงิน" description="ลองเปลี่ยนตัวกรองสถานะหรือช่วงวันที่" /> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] border-collapse text-left text-sm"><thead className="bg-[#faf8fc] text-[11px] text-muted"><tr><th className="px-5 py-3">รหัสจอง</th><th className="px-4 py-3">ผู้ขาย / ร้าน</th><th className="px-4 py-3">เหตุผล</th><th className="px-4 py-3">ยอด</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">บัญชีรับเงิน</th><th className="px-4 py-3">สร้างเมื่อ</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-[#eee9f3] align-top"><td className="px-5 py-4 font-black">{item.booking.bookingCode}</td><td className="px-4 py-4"><strong className="block">{item.booking.shop.name}</strong><span className="text-xs text-muted">{item.booking.vendor.fullName}</span></td><td className="max-w-xs px-4 py-4 text-muted">{item.reason}</td><td className="px-4 py-4"><strong className="block">ขอ {formatAdminMoney(item.requestedAmount)}</strong><span className="text-xs text-muted">อนุมัติ {item.approvedAmount ? formatAdminMoney(item.approvedAmount) : '—'}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${REFUND_STYLES[item.status]}`}>{item.status}</span>{item.payoutNameMismatch ? <span className="mt-1 block text-[10px] font-bold text-[#b42318]">ชื่อบัญชีควรตรวจสอบ</span> : null}</td><td className="px-4 py-4 text-xs text-muted">{item.payoutAccountName || '—'}<br />{item.payoutMethod || ''}</td><td className="px-4 py-4 text-xs text-muted">{formatAdminDateTime(item.createdAt)}</td></tr>)}</tbody></table></div>}
  </AdminPanel>;
}

function LoadingRows() { return <div className="grid gap-3 p-5">{Array.from({ length: 6 }, (_, index) => <div key={index} className="skeleton h-16 rounded-xl" />)}</div>; }
